# Generated by Django 3.2.3 on 2021-05-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_question_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_time',
        ),
    ]
